### ISSUE TITLE
Add file change log?

### ISSUE THREAD

**Issue by max-SS** [Ecodev/fab-speed-dial#6]
Hi, It would be great if you could add a **CHANGELOG.md** file, in which we can see the changes you are making, and in this way, thoroughly update it every time a new version is released.

**Comment by PowerKiKi** [comment]
Because this project is expect to have a relatively low volume of releases/changelogs, it will be maintained on https://github.com/Ecodev/fab-speed-dial/releases. And also, from now on, in the release annotated tags. That means changelog would locally be available with a command like `git tag -n99`.
